# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummytext',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
