# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20171028_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('ttl', 'Title'), ('sbt', 'Subtitle'), ('txt', 'Textarea'), ('vid', 'Video'), ('img', 'Image')], default='txt', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('small_text', models.CharField(max_length=100)),
                ('long_text', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
