# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='long_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='component',
            name='small_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
