# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_content_data'),
        ('components', '0005_auto_20171028_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
    ]
