# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_component_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='content.Content'),
        ),
    ]
