# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20171029_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('text', 'Textarea'), ('video', 'Video'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
