# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20171029_1707'),
        ('components', '0009_auto_20171114_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
    ]
