# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_remove_component_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='checkbox',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='components.CheckBoxComponent'),
        ),
        migrations.AddField(
            model_name='component',
            name='dropdown',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='components.DropdownComponent'),
        ),
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='components.ImageComponent'),
        ),
    ]
