# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20171116_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxcomponent',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropdowncomponent',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagecomponent',
            name='data',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='videocomponent',
            name='data',
            field=models.URLField(null=True),
        ),
    ]
