# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_auto_20171116_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomponent',
            name='data',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='content/'),
        ),
    ]
