# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_auto_20171128_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='checkbox',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.CheckBoxComponent'),
        ),
        migrations.AlterField(
            model_name='component',
            name='datetime',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.DateTimeComponent'),
        ),
        migrations.AlterField(
            model_name='component',
            name='dropdown',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.DropdownComponent'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.ImageComponent'),
        ),
        migrations.AlterField(
            model_name='component',
            name='longtext',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.LongTextComponent'),
        ),
        migrations.AlterField(
            model_name='component',
            name='number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.NumberComponent'),
        ),
        migrations.AlterField(
            model_name='component',
            name='text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.TextComponent'),
        ),
        migrations.AlterField(
            model_name='component',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='components.VideoComponent'),
        ),
    ]
