# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_auto_20171129_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=40)),
                ('checkbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='components.CheckBoxComponent')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=40)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='components.DropdownComponent')),
            ],
        ),
    ]
