# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_checkboxitem_dropdownitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdownitem',
            old_name='component',
            new_name='dropdown',
        ),
    ]
