# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_interestgroup_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgroup',
            name='content_types',
            field=models.ManyToManyField(related_name='group_contenttype', to='content.ContentType'),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='contents',
            field=models.ManyToManyField(related_name='group_content', to='content.Content'),
        ),
    ]
