# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20171029_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
