# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20171101_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgroup',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
