# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_auto_20171102_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestgroup',
            old_name='image',
            new_name='cover_photo',
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='waitings',
            field=models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='members',
            field=models.ManyToManyField(related_name='interest_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
