# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_auto_20171118_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestgroup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2017-11-16 16:55:24.935660+00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
