# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20171118_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgroup',
            name='waitings',
            field=models.ManyToManyField(related_name='group_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
