# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20171118_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgroup',
            name='content_types',
            field=models.ManyToManyField(related_name='groups', to='content.ContentType'),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='contents',
            field=models.ManyToManyField(related_name='groups', to='content.Content'),
        ),
    ]
