# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20171119_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestgroup',
            name='cover_img',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='images/group/'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='logo_img',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='images/group/'),
        ),
    ]
