# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20171128_2313'),
        ('recommendation', '0003_auto_20171128_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='related_group',
            field=models.ManyToManyField(related_name='content_tags', to='group.InterestGroup'),
        ),
    ]
