# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20171028_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('components', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), size=15)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ContentType'),
        ),
    ]
