# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 12:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20171029_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='components',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('text', 'Text'), ('longtext', 'Long Text'), ('number', 'Number'), ('datetime', 'Date/Time'), ('image', 'Image'), ('video', 'Video'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], max_length=10), size=15),
        ),
    ]
