# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 16:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20171115_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='component_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=15),
        ),
    ]
