# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20171119_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updown',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.Content'),
        ),
        migrations.AlterField(
            model_name='updown',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
