# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20171119_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
