# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_contenttype_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkboxes', to='content.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
                ('checkbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.CheckboxDefinition')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='content.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
                ('dropdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.DropdownDefinition')),
            ],
        ),
    ]
