# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('contects', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('facebook_account', models.CharField(blank=True, max_length=30, null=True)),
                ('twitter_account', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram_account', models.CharField(blank=True, max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
