# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contects',
            new_name='contacts',
        ),
    ]
