# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20171117_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other'), ('notspecified', 'Not-specified')], max_length=12, null=True),
        ),
    ]
