# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20171117_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
