# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_auto_20171128_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_requests',
            field=models.ManyToManyField(related_name='following_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
